version: '3.7'

services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:latest
    container_name: heylisten-db
    ports:
      - 3306:3306
    volumes:
      # save mariadb databases to named volume
      - database:/var/lib/mysql/
      # expose mariadb config to host
      - ./etc/:/docker/etc/
  web:
    image: 8ct8pus/nginx-php-fpm-alpine:latest
    container_name: heylisten-web
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=heylisten.app
      - DOCUMENT_ROOT=/api/public
    links:
      - mariadb
    volumes:
      # development directory
      - .:/var/www/site/
      # expose nginx logs to host
      - ./log/:/var/log/nginx/
      # expose nginx and php config to host
      - ./etc/:/docker/etc/
      # expose ssl certificates to host
      - ./ssl/:/etc/ssl/nginx/
volumes:
  database: